
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 PDO1_transmit_mask_PDO1_mask_LowerBytes = 0xFFFFFFFF;		/* Mapped at index 0x2014, subindex 0x01 */
UNS32 PDO1_transmit_mask_PDO1_mask_upperBytes = 0xFFFFFFFF;		/* Mapped at index 0x2014, subindex 0x02 */
UNS32 PDO2_transmit_mask_PDO2_mask_LowerBytes = 0xFFFFFFFF;		/* Mapped at index 0x2015, subindex 0x01 */
UNS32 PDO2_transmit_mask_PDO2_mask_upperBytes = 0xFFFFFFFF;		/* Mapped at index 0x2015, subindex 0x02 */
UNS32 PDO3_transmit_mask_PDO3_mask_LowerBytes = 0xFFFFFFFF;		/* Mapped at index 0x2016, subindex 0x01 */
UNS32 PDO3_transmit_mask_PDO3_mask_upperBytes = 0xFFFFFFFF;		/* Mapped at index 0x2016, subindex 0x02 */
UNS32 PDO4_transmit_mask_PDO4_mask_LowerBytes = 0xFFFFFFFF;		/* Mapped at index 0x2017, subindex 0x01 */
UNS32 PDO4_transmit_mask_PDO4_mask_upperBytes = 0xFFFFFFFF;		/* Mapped at index 0x2017, subindex 0x02 */
UNS8 Error_status_bits[10] = "0";		/* Mapped at index 0x2100, subindex 0x00 */
UNS8 CAN_node_ID = 0x30;		/* Mapped at index 0x2101, subindex 0x00 */
UNS16 CAN_bit_rate = 0xFA;		/* Mapped at index 0x2102, subindex 0x00 */
UNS16 SYNC_counter = 0x0;		/* Mapped at index 0x2103, subindex 0x00 */
UNS16 SYNC_time = 0x0;		/* Mapped at index 0x2104, subindex 0x00 */
UNS8 FWName[10] = "UNK";		/* Mapped at index 0x2200, subindex 0x00 */
UNS16 Switch_value = 0x0;		/* Mapped at index 0x3000, subindex 0x00 */
INTEGER32 UserRegisters_userRegister1 = 0x0;		/* Mapped at index 0x4000, subindex 0x01 */
INTEGER32 UserRegisters_userRegister2 = 0x0;		/* Mapped at index 0x4000, subindex 0x02 */
INTEGER32 UserRegisters_userRegister3 = 0x0;		/* Mapped at index 0x4000, subindex 0x03 */
INTEGER32 UserRegisters_userRegister4 = 0x0;		/* Mapped at index 0x4000, subindex 0x04 */
INTEGER32 UserRegisters_userRegister5 = 0x0;		/* Mapped at index 0x4000, subindex 0x05 */
INTEGER32 UserRegisters_userRegister6 = 0x0;		/* Mapped at index 0x4000, subindex 0x06 */
INTEGER32 UserRegisters_userRegister7 = 0x0;		/* Mapped at index 0x4000, subindex 0x07 */
INTEGER32 UserRegisters_userRegister8 = 0x0;		/* Mapped at index 0x4000, subindex 0x08 */
INTEGER32 UserRegisters_userRegister9 = 0x0;		/* Mapped at index 0x4000, subindex 0x09 */
INTEGER32 UserRegisters_userRegister10 = 0x0;		/* Mapped at index 0x4000, subindex 0x0A */
INTEGER32 UserRegisters_userRegister11 = 0x0;		/* Mapped at index 0x4000, subindex 0x0B */
INTEGER32 UserRegisters_userRegister12 = 0x0;		/* Mapped at index 0x4000, subindex 0x0C */
INTEGER32 UserRegisters_userRegister13 = 0x0;		/* Mapped at index 0x4000, subindex 0x0D */
INTEGER32 UserRegisters_userRegister14 = 0x0;		/* Mapped at index 0x4000, subindex 0x0E */
INTEGER32 UserRegisters_userRegister15 = 0x0;		/* Mapped at index 0x4000, subindex 0x0F */
INTEGER32 UserRegisters_userRegister16 = 0x0;		/* Mapped at index 0x4000, subindex 0x10 */
INTEGER32 UserRegisters_userRegister17 = 0x0;		/* Mapped at index 0x4000, subindex 0x11 */
INTEGER32 UserRegisters_userRegister18 = 0x0;		/* Mapped at index 0x4000, subindex 0x12 */
INTEGER32 UserRegisters_userRegister19 = 0x0;		/* Mapped at index 0x4000, subindex 0x13 */
INTEGER32 UserRegisters_userRegister20 = 0x0;		/* Mapped at index 0x4000, subindex 0x14 */
INTEGER32 UserRegisters_userRegister21 = 0x0;		/* Mapped at index 0x4000, subindex 0x15 */
INTEGER32 UserRegisters_userRegister22 = 0x0;		/* Mapped at index 0x4000, subindex 0x16 */
INTEGER32 UserRegisters_userRegister23 = 0x0;		/* Mapped at index 0x4000, subindex 0x17 */
UNS16 Global_Gain = 0x0;		/* Mapped at index 0x5400, subindex 0x00 */
UNS16 Global_Gain_Snd = 0x0;		/* Mapped at index 0x5401, subindex 0x00 */
UNS16 Proportion_Gain = 0x0;		/* Mapped at index 0x5402, subindex 0x00 */
UNS16 Damping_Gain = 0x0;		/* Mapped at index 0x5403, subindex 0x00 */
UNS16 Velocity_Gain = 0x0;		/* Mapped at index 0x5404, subindex 0x00 */
UNS16 VelocityInteg_Gain = 0x0;		/* Mapped at index 0x5405, subindex 0x00 */
UNS16 AccFeedforward_Gain = 0x0;		/* Mapped at index 0x5406, subindex 0x00 */
UNS16 Jerk_Hz = 0x0;		/* Mapped at index 0x5407, subindex 0x00 */
UNS16 ProGain_VelocityMode = 0x0;		/* Mapped at index 0x5408, subindex 0x00 */
UNS16 IntegGain_VelocityMode = 0x0;		/* Mapped at index 0x5409, subindex 0x00 */
UNS16 DampingFilter_Gain = 0x0;		/* Mapped at index 0x540A, subindex 0x00 */
UNS16 CurrentFilter_Gain = 0x0;		/* Mapped at index 0x540B, subindex 0x00 */
UNS16 MaxVelocity = 0x0;		/* Mapped at index 0x540C, subindex 0x00 */
UNS16 MaxAccel = 0x0;		/* Mapped at index 0x540D, subindex 0x00 */
UNS16 JogSpeed = 0x0;		/* Mapped at index 0x540E, subindex 0x00 */
UNS16 Jog_Accel = 0x0;		/* Mapped at index 0x540F, subindex 0x00 */
UNS16 Jog_Decel = 0x0;		/* Mapped at index 0x5410, subindex 0x00 */
UNS16 P2P_Velocity = 0x0;		/* Mapped at index 0x5411, subindex 0x00 */
UNS16 P2P_Accel = 0x0;		/* Mapped at index 0x5412, subindex 0x00 */
UNS16 P2P_Decel = 0x0;		/* Mapped at index 0x5413, subindex 0x00 */
UNS16 P2P_ChgVelocity = 0x0;		/* Mapped at index 0x5414, subindex 0x00 */
UNS16 Jog_ChgVelocity_ChgSpeed0 = 0x0;		/* Mapped at index 0x5415, subindex 0x01 */
UNS16 Jog_ChgVelocity_ChgSpeed2 = 0x0;		/* Mapped at index 0x5415, subindex 0x02 */
UNS16 Jog_ChgVelocity_ChgSpeed3 = 0x0;		/* Mapped at index 0x5415, subindex 0x03 */
UNS16 Jog_ChgVelocity_ChgSpeed4 = 0x0;		/* Mapped at index 0x5415, subindex 0x04 */
UNS16 Jog_ChgVelocity_ChgSpeed5 = 0x0;		/* Mapped at index 0x5415, subindex 0x05 */
UNS16 Jog_ChgVelocity_ChgSpeed6 = 0x0;		/* Mapped at index 0x5415, subindex 0x06 */
UNS16 Jog_ChgVelocity_ChgSpeed7 = 0x0;		/* Mapped at index 0x5415, subindex 0x07 */
UNS16 Jog_ChgVelocity_ChgSpeed8 = 0x0;		/* Mapped at index 0x5415, subindex 0x08 */
UNS16 Encoder_Res = 0x0;		/* Mapped at index 0x5416, subindex 0x00 */
UNS16 FullEncoder_Res = 0x0;		/* Mapped at index 0x5417, subindex 0x00 */
UNS16 Step_Rev = 0x0;		/* Mapped at index 0x5418, subindex 0x00 */
UNS16 Step_Rev_Snd = 0x0;		/* Mapped at index 0x5419, subindex 0x00 */
UNS16 Elec_Ratio_N = 0x0;		/* Mapped at index 0x541A, subindex 0x00 */
UNS16 Elec_Ratio_D = 0x0;		/* Mapped at index 0x541B, subindex 0x00 */
UNS16 StepMode = 0x0;		/* Mapped at index 0x541C, subindex 0x00 */
UNS16 PositionFault_Window = 0x0;		/* Mapped at index 0x541D, subindex 0x00 */
UNS16 InPositionCounts = 0x0;		/* Mapped at index 0x541E, subindex 0x00 */
UNS16 PosErr_Range = 0x0;		/* Mapped at index 0x541F, subindex 0x00 */
UNS16 InPos_ContTime = 0x0;		/* Mapped at index 0x5420, subindex 0x00 */
UNS16 AnalogOffset_AnalogOffset1 = 0x0;		/* Mapped at index 0x5421, subindex 0x01 */
UNS16 AnalogOffset_AnalogOffset2 = 0x0;		/* Mapped at index 0x5421, subindex 0x02 */
UNS16 AnalogOffset_AnalogOffset3 = 0x0;		/* Mapped at index 0x5421, subindex 0x03 */
UNS16 AnalogType = 0x0;		/* Mapped at index 0x5422, subindex 0x00 */
UNS16 AnalogDeadband_AnalogDeadband1 = 0x0;		/* Mapped at index 0x5423, subindex 0x01 */
UNS16 AnalogDeadband_AnalogDeadband2 = 0x0;		/* Mapped at index 0x5423, subindex 0x02 */
UNS16 AnalogDeadband_AnalogDeadband3 = 0x0;		/* Mapped at index 0x5423, subindex 0x03 */
UNS16 AnalogFilterGain = 0x0;		/* Mapped at index 0x5424, subindex 0x00 */
UNS16 ServoEnable = 0x0;		/* Mapped at index 0x5425, subindex 0x00 */
UNS16 AlarmResetInput = 0x0;		/* Mapped at index 0x5426, subindex 0x00 */
UNS16 DefineLimits = 0x0;		/* Mapped at index 0x5427, subindex 0x00 */
UNS16 GlobalGain_Selection = 0x0;		/* Mapped at index 0x5428, subindex 0x00 */
UNS16 AlarmOutput = 0x0;		/* Mapped at index 0x5429, subindex 0x00 */
UNS16 BrakeOutput = 0x0;		/* Mapped at index 0x542A, subindex 0x00 */
UNS16 MoveOutput_MoveOutput1 = 0x0;		/* Mapped at index 0x542B, subindex 0x01 */
UNS16 MoveOutput_MoveOutput2 = 0x0;		/* Mapped at index 0x542B, subindex 0x02 */
UNS16 MoveOutput_MoveOutput3 = 0x0;		/* Mapped at index 0x542B, subindex 0x03 */
UNS16 MoveOutput_MoveOutput4 = 0x0;		/* Mapped at index 0x542B, subindex 0x04 */
UNS16 BrakeDisengage_Delay = 0x0;		/* Mapped at index 0x542C, subindex 0x00 */
UNS16 BrakeEngage_Delay = 0x0;		/* Mapped at index 0x542D, subindex 0x00 */
UNS16 Inputs_Filter_FilterInput1 = 0x0;		/* Mapped at index 0x542E, subindex 0x01 */
UNS16 Inputs_Filter_FilterInput2 = 0x0;		/* Mapped at index 0x542E, subindex 0x02 */
UNS16 Inputs_Filter_FilterInput3 = 0x0;		/* Mapped at index 0x542E, subindex 0x03 */
UNS16 Inputs_Filter_FilterInput4 = 0x0;		/* Mapped at index 0x542E, subindex 0x04 */
UNS16 NodeID = 0x0;		/* Mapped at index 0x542F, subindex 0x00 */
UNS16 BaudRate = 0x0;		/* Mapped at index 0x5430, subindex 0x00 */
UNS16 Clamp_para_Clamp_res = 0x0;		/* Mapped at index 0x5431, subindex 0x01 */
UNS16 Clamp_para_Clamp_cont = 0x0;		/* Mapped at index 0x5431, subindex 0x02 */
UNS16 Clamp_para_Clamp_time = 0x0;		/* Mapped at index 0x5431, subindex 0x03 */
UNS16 VelocityReach_window = 0x0;		/* Mapped at index 0x5432, subindex 0x00 */
UNS16 TorqueReach_window = 0x0;		/* Mapped at index 0x5433, subindex 0x00 */
UNS16 TachOutput = 0x0;		/* Mapped at index 0x5434, subindex 0x00 */
UNS16 JogMode = 0x0;		/* Mapped at index 0x5435, subindex 0x00 */
UNS16 AlarmMask = 0x0;		/* Mapped at index 0x5436, subindex 0x00 */
UNS16 DSP_Error_Code = 0x0;		/* Mapped at index 0x603F, subindex 0x00 */
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER16 Quick_stop_option_code = 0x0;		/* Mapped at index 0x605A, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
UNS32 Maximal_following_error = 0x0;		/* Mapped at index 0x6065, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER16 target_torque = 0x0;		/* Mapped at index 0x6071, subindex 0x00 */
UNS16 max_current = 0x0;		/* Mapped at index 0x6073, subindex 0x00 */
INTEGER16 torque_demand_value = 0x0;		/* Mapped at index 0x6074, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Home_offset = 0x0;		/* Mapped at index 0x607C, subindex 0x00 */
UNS8 polarity = 0x0;		/* Mapped at index 0x607E, subindex 0x00 */
UNS32 Maximal_profile_velocity = 0x0;		/* Mapped at index 0x607F, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
UNS32 Profile_acceleration = 0x0;		/* Mapped at index 0x6083, subindex 0x00 */
UNS32 Profile_deceleration = 0x0;		/* Mapped at index 0x6084, subindex 0x00 */
UNS32 Quick_stop_deceleration = 0x0;		/* Mapped at index 0x6085, subindex 0x00 */
UNS32 torque_slope = 0x0;		/* Mapped at index 0x6087, subindex 0x00 */
INTEGER8 Homing_method = 0x0;		/* Mapped at index 0x6098, subindex 0x00 */
UNS32 Homing_speeds_Speed_for_switch_search = 0x0;		/* Mapped at index 0x6099, subindex 0x01 */
UNS32 Homing_speeds_Speed_for_zero_search = 0x0;		/* Mapped at index 0x6099, subindex 0x02 */
UNS32 Homing_acceleration = 0x0;		/* Mapped at index 0x609A, subindex 0x00 */
INTEGER32 pos_err_actual_value = 0x0;		/* Mapped at index 0x60F4, subindex 0x00 */
UNS32 digital_outputs_physical_outputs = 0x0;		/* Mapped at index 0x60FE, subindex 0x01 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */
UNS32 Supported_drive_modes = 0x0;		/* Mapped at index 0x6502, subindex 0x00 */
UNS8 home_switch = 0x3;		/* Mapped at index 0x7001, subindex 0x00 */
UNS16 idle_current = 0x0;		/* Mapped at index 0x7002, subindex 0x00 */
UNS16 drive_inputs = 0x0;		/* Mapped at index 0x7003, subindex 0x00 */
UNS16 torque_Constant = 0x0;		/* Mapped at index 0x7005, subindex 0x00 */
UNS8 DSP_clearAlarm = 0x0;		/* Mapped at index 0x7006, subindex 0x00 */
UNS8 QSegment = 0x0;		/* Mapped at index 0x7007, subindex 0x00 */
UNS16 velocity_actual_value = 0x0;		/* Mapped at index 0x7009, subindex 0x00 */
INTEGER32 position_actual_value = 0x0;		/* Mapped at index 0x700A, subindex 0x00 */
UNS16 DSP_statuscode = 0x0;		/* Mapped at index 0x700B, subindex 0x00 */
UNS8 zero_Position = 0x0;		/* Mapped at index 0x700C, subindex 0x00 */
UNS16 Acceleration_Current = 0x0;		/* Mapped at index 0x700D, subindex 0x00 */
UNS16 Analog_Input1 = 0x0;		/* Mapped at index 0x700E, subindex 0x00 */
UNS16 AlarmCodeUpper = 0x0;		/* Mapped at index 0x700F, subindex 0x00 */
UNS16 HardStopCurrent = 0x0;		/* Mapped at index 0x7010, subindex 0x00 */
UNS16 Peak_Current = 0x0;		/* Mapped at index 0x7011, subindex 0x00 */
UNS16 Driver_Temperature = 0x0;		/* Mapped at index 0x7012, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 _valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 _bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 _iam_a_slave = 1;

TIMER_HANDLE _heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 _obj1000 = 0x60192;	/* 393618 */
                    subindex _Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 _obj1001 = 0x0;	/* 0 */
                    subindex _Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_obj1001 }
                     };

/* index 0x1002 :   Manufacturer Status Register. */
                    UNS32 _obj1002 = 0x0;	/* 0 */
                    subindex _Index1002[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1002 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 _highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 _obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t _Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[1] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[2] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[3] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[4] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[5] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[6] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[7] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 _obj1005 = 0x80;	/* 128 */
                    ODCallback_t _Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 _obj1006 = 0x0;	/* 0 */
                    ODCallback_t _Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1006 }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 _obj1007 = 0x0;	/* 0 */
                    subindex _Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1007 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 _obj1008[24] = "AMA CANopen Motor Driver";
                    subindex _Index1008[] = 
                     {
                       { RO, visible_string, 24, (void*)&_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 _obj1009[10] = "3.00";
                    subindex _Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 _obj100A[10] = "2.12";
                    subindex _Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&_obj100A }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 _obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 _obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 _highestSubIndex_obj1010 = 2; /* number of subindex - 1*/
                    UNS32 _obj1010_Save_All_Parameters = 0x3;	/* 3 */
                    UNS32 _obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    subindex _Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_Communication_Parameters }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 _highestSubIndex_obj1011 = 2; /* number of subindex - 1*/
                    UNS32 _obj1011_Restore_All_Default_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    subindex _Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_Communication_Default_Parameters }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 _obj1014 = 0x80;	/* 128 */
                    subindex _Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1014 }
                     };

/* index 0x1015 :   Inhibit Time Emergency. */
                    UNS16 _obj1015 = 0xC8;	/* 200 */
                    subindex _Index1015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1015 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 _highestSubIndex_obj1016 = 0;
                    UNS32 _obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 _obj1017 = 0x3E8;	/* 1000 */
                    ODCallback_t _Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 _highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 _obj1018_Vendor_ID = 0x2D9;	/* 729 */
                    UNS32 _obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 _obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 _obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex _Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Serial_Number }
                     };

/* index 0x1019 :   Synchronous counter overflow value. */
                    UNS8 _obj1019 = 0x0;	/* 0 */
                    subindex _Index1019[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1019 }
                     };

/* index 0x1029 :   Error Behavior. */
                    UNS8 _highestSubIndex_obj1029 = 6; /* number of subindex - 1*/
                    UNS8 _obj1029_Communication_Error = 0x0;	/* 0 */
                    UNS8 _obj1029_Device_Profile1 = 0x0;	/* 0 */
                    UNS8 _obj1029_Device_Profile2 = 0x1;	/* 1 */
                    UNS8 _obj1029_Device_Profile3 = 0x0;	/* 0 */
                    UNS8 _obj1029_Device_Profile4 = 0x0;	/* 0 */
                    UNS8 _obj1029_Device_Profile5 = 0x0;	/* 0 */
                    subindex _Index1029[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1029 },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1029_Communication_Error },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1029_Device_Profile1 },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1029_Device_Profile2 },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1029_Device_Profile3 },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1029_Device_Profile4 },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1029_Device_Profile5 }
                     };
#if 0
/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 _highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 _obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 _obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex _Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };
#endif										 
										 
/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 example_objdict_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 example_objdict_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x600;	/* 0 */
                    UNS32 example_objdict_obj1280_COB_ID_Server_to_Client_Receive_SDO  = 0x580;	/* 0 */
                    UNS8 example_objdict_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 0 */
                    subindex example_objdict_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&example_objdict_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&example_objdict_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&example_objdict_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&example_objdict_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1400 = 2; /* number of subindex - 1*/
                    UNS32 _obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 _obj1400_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1400_Transmission_Type }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 _highestSubIndex_obj1401 = 2; /* number of subindex - 1*/
                    UNS32 _obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 _obj1401_Transmission_Type = 0xFE;	/* 254 */
                    subindex _Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1401_Transmission_Type }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 _highestSubIndex_obj1402 = 2; /* number of subindex - 1*/
                    UNS32 _obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 _obj1402_Transmission_Type = 0xFE;	/* 254 */
                    subindex _Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1402_Transmission_Type }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 _highestSubIndex_obj1403 = 2; /* number of subindex - 1*/
                    UNS32 _obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 _obj1403_Transmission_Type = 0xFE;	/* 254 */
                    subindex _Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1403_Transmission_Type }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 _highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 _obj1600[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 _highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 _obj1601[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x607A0020,	/* 1618608160 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 _highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 _obj1602[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x60FF0020,	/* 1627324448 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 _highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 _obj1603[] = 
                    {
                      0x60FE0120,	/* 1627259168 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 _obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 _obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1800_Inhibit_Time = 0x64;	/* 100 */
                    UNS8 _obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 _highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 _obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 _obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 _highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 _obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 _obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 _highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 _obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 _obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 _highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 _obj1A00[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 _highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 _obj1A01[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x700A0020,	/* 1879703584 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 _highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 _obj1A02[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x70090010,	/* 1879638032 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 _highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 _obj1A03[] = 
                    {
                      0x70030010,	/* 1879244816 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[7] }
                     };

/* index 0x1F80 :   NMT startup. */
                    UNS32 _obj1F80 = 0x0;	/* 0 */
                    subindex _Index1F80[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1F80 }
                     };

/* index 0x2014 :   Mapped variable PDO1_transmit_mask */
                    UNS8 _highestSubIndex_obj2014 = 2; /* number of subindex - 1*/
                    subindex _Index2014[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2014 },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO1_transmit_mask_PDO1_mask_LowerBytes },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO1_transmit_mask_PDO1_mask_upperBytes }
                     };

/* index 0x2015 :   Mapped variable PDO2_transmit_mask */
                    UNS8 _highestSubIndex_obj2015 = 2; /* number of subindex - 1*/
                    subindex _Index2015[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2015 },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO2_transmit_mask_PDO2_mask_LowerBytes },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO2_transmit_mask_PDO2_mask_upperBytes }
                     };

/* index 0x2016 :   Mapped variable PDO3_transmit_mask */
                    UNS8 _highestSubIndex_obj2016 = 2; /* number of subindex - 1*/
                    subindex _Index2016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2016 },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO3_transmit_mask_PDO3_mask_LowerBytes },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO3_transmit_mask_PDO3_mask_upperBytes }
                     };

/* index 0x2017 :   Mapped variable PDO4_transmit_mask */
                    UNS8 _highestSubIndex_obj2017 = 2; /* number of subindex - 1*/
                    subindex _Index2017[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2017 },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO4_transmit_mask_PDO4_mask_LowerBytes },
                       { RW, uint32, sizeof (UNS32), (void*)&PDO4_transmit_mask_PDO4_mask_upperBytes }
                     };

/* index 0x2100 :   Mapped variable Error status bits */
                    subindex _Index2100[] = 
                     {
                       { RO, visible_string, 10, (void*)&Error_status_bits }
                     };

/* index 0x2101 :   Mapped variable CAN node ID */
                    subindex _Index2101[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_node_ID }
                     };

/* index 0x2102 :   Mapped variable CAN bit rate */
                    subindex _Index2102[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_bit_rate }
                     };

/* index 0x2103 :   Mapped variable SYNC counter */
                    subindex _Index2103[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SYNC_counter }
                     };

/* index 0x2104 :   Mapped variable SYNC time */
                    subindex _Index2104[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&SYNC_time }
                     };

/* index 0x2200 :   Mapped variable FWName */
                    subindex _Index2200[] = 
                     {
                       { RO, visible_string, 10, (void*)&FWName }
                     };

/* index 0x3000 :   Mapped variable Switch value */
                    subindex _Index3000[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Switch_value }
                     };

/* index 0x4000 :   Mapped variable UserRegisters */
                    UNS8 _highestSubIndex_obj4000 = 23; /* number of subindex - 1*/
                    subindex _Index4000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj4000 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister1 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister2 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister3 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister4 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister5 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister6 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister7 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister8 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister9 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister10 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister11 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister12 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister13 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister14 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister15 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister16 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister17 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister18 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister19 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister20 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister21 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister22 },
                       { RW, int32, sizeof (INTEGER32), (void*)&UserRegisters_userRegister23 }
                     };

/* index 0x5400 :   Mapped variable Global_Gain */
                    subindex _Index5400[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Global_Gain }
                     };

/* index 0x5401 :   Mapped variable Global_Gain_Snd */
                    subindex _Index5401[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Global_Gain_Snd }
                     };

/* index 0x5402 :   Mapped variable Proportion_Gain */
                    subindex _Index5402[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Proportion_Gain }
                     };

/* index 0x5403 :   Mapped variable Damping_Gain */
                    subindex _Index5403[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Damping_Gain }
                     };

/* index 0x5404 :   Mapped variable Velocity_Gain */
                    subindex _Index5404[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Velocity_Gain }
                     };

/* index 0x5405 :   Mapped variable VelocityInteg_Gain */
                    subindex _Index5405[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&VelocityInteg_Gain }
                     };

/* index 0x5406 :   Mapped variable AccFeedforward_Gain */
                    subindex _Index5406[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AccFeedforward_Gain }
                     };

/* index 0x5407 :   Mapped variable Jerk_Hz */
                    subindex _Index5407[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Jerk_Hz }
                     };

/* index 0x5408 :   Mapped variable ProGain_VelocityMode */
                    subindex _Index5408[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ProGain_VelocityMode }
                     };

/* index 0x5409 :   Mapped variable IntegGain_VelocityMode */
                    subindex _Index5409[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&IntegGain_VelocityMode }
                     };

/* index 0x540A :   Mapped variable DampingFilter_Gain */
                    subindex _Index540A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&DampingFilter_Gain }
                     };

/* index 0x540B :   Mapped variable CurrentFilter_Gain */
                    subindex _Index540B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CurrentFilter_Gain }
                     };

/* index 0x540C :   Mapped variable MaxVelocity */
                    subindex _Index540C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MaxVelocity }
                     };

/* index 0x540D :   Mapped variable MaxAccel */
                    subindex _Index540D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MaxAccel }
                     };

/* index 0x540E :   Mapped variable JogSpeed */
                    subindex _Index540E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&JogSpeed }
                     };

/* index 0x540F :   Mapped variable Jog_Accel */
                    subindex _Index540F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_Accel }
                     };

/* index 0x5410 :   Mapped variable Jog_Decel */
                    subindex _Index5410[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_Decel }
                     };

/* index 0x5411 :   Mapped variable P2P_Velocity */
                    subindex _Index5411[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&P2P_Velocity }
                     };

/* index 0x5412 :   Mapped variable P2P_Accel */
                    subindex _Index5412[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&P2P_Accel }
                     };

/* index 0x5413 :   Mapped variable P2P_Decel */
                    subindex _Index5413[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&P2P_Decel }
                     };

/* index 0x5414 :   Mapped variable P2P_ChgVelocity */
                    subindex _Index5414[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&P2P_ChgVelocity }
                     };

/* index 0x5415 :   Mapped variable Jog_ChgVelocity */
                    UNS8 _highestSubIndex_obj5415 = 8; /* number of subindex - 1*/
                    subindex _Index5415[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj5415 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed0 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed3 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed4 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed5 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed6 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed7 },
                       { RW, uint16, sizeof (UNS16), (void*)&Jog_ChgVelocity_ChgSpeed8 }
                     };

/* index 0x5416 :   Mapped variable Encoder_Res */
                    subindex _Index5416[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Encoder_Res }
                     };

/* index 0x5417 :   Mapped variable FullEncoder_Res */
                    subindex _Index5417[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&FullEncoder_Res }
                     };

/* index 0x5418 :   Mapped variable Step_Rev */
                    subindex _Index5418[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Step_Rev }
                     };

/* index 0x5419 :   Mapped variable Step_Rev_Snd */
                    subindex _Index5419[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Step_Rev_Snd }
                     };

/* index 0x541A :   Mapped variable Elec_Ratio_N */
                    subindex _Index541A[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Elec_Ratio_N }
                     };

/* index 0x541B :   Mapped variable Elec_Ratio_D */
                    subindex _Index541B[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Elec_Ratio_D }
                     };

/* index 0x541C :   Mapped variable StepMode */
                    subindex _Index541C[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&StepMode }
                     };

/* index 0x541D :   Mapped variable PositionFault_Window */
                    subindex _Index541D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PositionFault_Window }
                     };

/* index 0x541E :   Mapped variable InPositionCounts */
                    subindex _Index541E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&InPositionCounts }
                     };

/* index 0x541F :   Mapped variable PosErr_Range */
                    subindex _Index541F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PosErr_Range }
                     };

/* index 0x5420 :   Mapped variable InPos_ContTime */
                    subindex _Index5420[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&InPos_ContTime }
                     };

/* index 0x5421 :   Mapped variable AnalogOffset */
                    UNS8 _highestSubIndex_obj5421 = 3; /* number of subindex - 1*/
                    subindex _Index5421[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj5421 },
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogOffset_AnalogOffset1 },
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogOffset_AnalogOffset2 },
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogOffset_AnalogOffset3 }
                     };

/* index 0x5422 :   Mapped variable AnalogType */
                    subindex _Index5422[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogType }
                     };

/* index 0x5423 :   Mapped variable AnalogDeadband */
                    UNS8 _highestSubIndex_obj5423 = 3; /* number of subindex - 1*/
                    subindex _Index5423[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj5423 },
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogDeadband_AnalogDeadband1 },
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogDeadband_AnalogDeadband2 },
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogDeadband_AnalogDeadband3 }
                     };

/* index 0x5424 :   Mapped variable AnalogFilterGain */
                    subindex _Index5424[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AnalogFilterGain }
                     };

/* index 0x5425 :   Mapped variable ServoEnable */
                    subindex _Index5425[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ServoEnable }
                     };

/* index 0x5426 :   Mapped variable AlarmResetInput */
                    subindex _Index5426[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AlarmResetInput }
                     };

/* index 0x5427 :   Mapped variable DefineLimits */
                    subindex _Index5427[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&DefineLimits }
                     };

/* index 0x5428 :   Mapped variable GlobalGain_Selection */
                    subindex _Index5428[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&GlobalGain_Selection }
                     };

/* index 0x5429 :   Mapped variable AlarmOutput */
                    subindex _Index5429[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AlarmOutput }
                     };

/* index 0x542A :   Mapped variable BrakeOutput */
                    subindex _Index542A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BrakeOutput }
                     };

/* index 0x542B :   Mapped variable MoveOutput */
                    UNS8 _highestSubIndex_obj542B = 4; /* number of subindex - 1*/
                    subindex _Index542B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj542B },
                       { RW, uint16, sizeof (UNS16), (void*)&MoveOutput_MoveOutput1 },
                       { RW, uint16, sizeof (UNS16), (void*)&MoveOutput_MoveOutput2 },
                       { RW, uint16, sizeof (UNS16), (void*)&MoveOutput_MoveOutput3 },
                       { RW, uint16, sizeof (UNS16), (void*)&MoveOutput_MoveOutput4 }
                     };

/* index 0x542C :   Mapped variable BrakeDisengage_Delay */
                    subindex _Index542C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BrakeDisengage_Delay }
                     };

/* index 0x542D :   Mapped variable BrakeEngage_Delay */
                    subindex _Index542D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BrakeEngage_Delay }
                     };

/* index 0x542E :   Mapped variable Inputs_Filter */
                    UNS8 _highestSubIndex_obj542E = 4; /* number of subindex - 1*/
                    subindex _Index542E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj542E },
                       { RW, uint16, sizeof (UNS16), (void*)&Inputs_Filter_FilterInput1 },
                       { RW, uint16, sizeof (UNS16), (void*)&Inputs_Filter_FilterInput2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Inputs_Filter_FilterInput3 },
                       { RW, uint16, sizeof (UNS16), (void*)&Inputs_Filter_FilterInput4 }
                     };

/* index 0x542F :   Mapped variable NodeID */
                    subindex _Index542F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&NodeID }
                     };

/* index 0x5430 :   Mapped variable BaudRate */
                    subindex _Index5430[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BaudRate }
                     };

/* index 0x5431 :   Mapped variable Clamp_para */
                    UNS8 _highestSubIndex_obj5431 = 3; /* number of subindex - 1*/
                    subindex _Index5431[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj5431 },
                       { RW, uint16, sizeof (UNS16), (void*)&Clamp_para_Clamp_res },
                       { RW, uint16, sizeof (UNS16), (void*)&Clamp_para_Clamp_cont },
                       { RW, uint16, sizeof (UNS16), (void*)&Clamp_para_Clamp_time }
                     };

/* index 0x5432 :   Mapped variable VelocityReach_window */
                    subindex _Index5432[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&VelocityReach_window }
                     };

/* index 0x5433 :   Mapped variable TorqueReach_window */
                    subindex _Index5433[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TorqueReach_window }
                     };

/* index 0x5434 :   Mapped variable TachOutput */
                    subindex _Index5434[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TachOutput }
                     };

/* index 0x5435 :   Mapped variable JogMode */
                    subindex _Index5435[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&JogMode }
                     };

/* index 0x5436 :   Mapped variable AlarmMask */
                    subindex _Index5436[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AlarmMask }
                     };

/* index 0x603F :   Mapped variable DSP Error Code */
                    subindex _Index603F[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&DSP_Error_Code }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex _Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex _Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword }
                     };

/* index 0x605A :   Mapped variable Quick_stop_option_code */
                    subindex _Index605A[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Quick_stop_option_code }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex _Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation }
                     };

/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex _Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex _Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value }
                     };

/* index 0x6065 :   Mapped variable Maximal following error */
                    subindex _Index6065[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_following_error }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex _Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value }
                     };

/* index 0x6071 :   Mapped variable target_torque */
                    subindex _Index6071[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&target_torque }
                     };

/* index 0x6073 :   Mapped variable max_current */
                    subindex _Index6073[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&max_current }
                     };

/* index 0x6074 :   Mapped variable torque_demand_value */
                    subindex _Index6074[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&torque_demand_value }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex _Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex _Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position }
                     };

/* index 0x607C :   Mapped variable Home offset */
                    subindex _Index607C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Home_offset }
                     };

/* index 0x607E :   Mapped variable polarity */
                    subindex _Index607E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&polarity }
                     };

/* index 0x607F :   Mapped variable Maximal profile velocity */
                    subindex _Index607F[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_profile_velocity }
                     };

/* index 0x6081 :   Mapped variable Profile velocity */
                    subindex _Index6081[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_velocity }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex _Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration }
                     };

/* index 0x6084 :   Mapped variable Profile deceleration */
                    subindex _Index6084[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_deceleration }
                     };

/* index 0x6085 :   Mapped variable Quick stop deceleration */
                    subindex _Index6085[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Quick_stop_deceleration }
                     };

/* index 0x6087 :   Mapped variable torque_slope */
                    subindex _Index6087[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&torque_slope }
                     };

/* index 0x6098 :   Mapped variable Homing method */
                    subindex _Index6098[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_method }
                     };

/* index 0x6099 :   Mapped variable Homing speeds */
                    UNS8 _highestSubIndex_obj6099 = 2; /* number of subindex - 1*/
                    subindex _Index6099[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj6099 },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_switch_search },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_zero_search }
                     };

/* index 0x609A :   Mapped variable Homing acceleration */
                    subindex _Index609A[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_acceleration }
                     };

/* index 0x60F4 :   Mapped variable pos_err_actual_value */
                    subindex _Index60F4[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&pos_err_actual_value }
                     };

/* index 0x60FE :   Mapped variable digital_outputs */
                    UNS8 _highestSubIndex_obj60FE = 1; /* number of subindex - 1*/
                    subindex _Index60FE[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj60FE },
                       { RW, uint32, sizeof (UNS32), (void*)&digital_outputs_physical_outputs }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex _Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity }
                     };

/* index 0x6502 :   Mapped variable Supported drive modes */
                    subindex _Index6502[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Supported_drive_modes }
                     };

/* index 0x7001 :   Mapped variable home_switch */
                    subindex _Index7001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&home_switch }
                     };

/* index 0x7002 :   Mapped variable idle_current */
                    subindex _Index7002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&idle_current }
                     };

/* index 0x7003 :   Mapped variable drive_inputs */
                    subindex _Index7003[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&drive_inputs }
                     };

/* index 0x7005 :   Mapped variable torque_Constant */
                    subindex _Index7005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&torque_Constant }
                     };

/* index 0x7006 :   Mapped variable DSP_clearAlarm */
                    subindex _Index7006[] = 
                     {
                       { WO, uint8, sizeof (UNS8), (void*)&DSP_clearAlarm }
                     };

/* index 0x7007 :   Mapped variable QSegment */
                    subindex _Index7007[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&QSegment }
                     };

/* index 0x7009 :   Mapped variable velocity_actual_value */
                    subindex _Index7009[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&velocity_actual_value }
                     };

/* index 0x700A :   Mapped variable position_actual_value */
                    subindex _Index700A[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&position_actual_value }
                     };

/* index 0x700B :   Mapped variable DSP_statuscode */
                    subindex _Index700B[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&DSP_statuscode }
                     };

/* index 0x700C :   Mapped variable zero_Position */
                    subindex _Index700C[] = 
                     {
                       { WO, uint8, sizeof (UNS8), (void*)&zero_Position }
                     };

/* index 0x700D :   Mapped variable Acceleration_Current */
                    subindex _Index700D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Acceleration_Current }
                     };

/* index 0x700E :   Mapped variable Analog_Input1 */
                    subindex _Index700E[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_Input1 }
                     };

/* index 0x700F :   Mapped variable AlarmCodeUpper */
                    subindex _Index700F[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&AlarmCodeUpper }
                     };

/* index 0x7010 :   Mapped variable HardStopCurrent */
                    subindex _Index7010[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&HardStopCurrent }
                     };

/* index 0x7011 :   Mapped variable Peak Current */
                    subindex _Index7011[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Peak_Current }
                     };

/* index 0x7012 :   Mapped variable Driver_Temperature */
                    subindex _Index7012[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Driver_Temperature }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable _objdict[] = 
{
  { (subindex*)_Index1000,sizeof(_Index1000)/sizeof(_Index1000[0]), 0x1000},
  { (subindex*)_Index1001,sizeof(_Index1001)/sizeof(_Index1001[0]), 0x1001},
  { (subindex*)_Index1002,sizeof(_Index1002)/sizeof(_Index1002[0]), 0x1002},
  { (subindex*)_Index1003,sizeof(_Index1003)/sizeof(_Index1003[0]), 0x1003},
  { (subindex*)_Index1005,sizeof(_Index1005)/sizeof(_Index1005[0]), 0x1005},
  { (subindex*)_Index1006,sizeof(_Index1006)/sizeof(_Index1006[0]), 0x1006},
  { (subindex*)_Index1007,sizeof(_Index1007)/sizeof(_Index1007[0]), 0x1007},
  { (subindex*)_Index1008,sizeof(_Index1008)/sizeof(_Index1008[0]), 0x1008},
  { (subindex*)_Index1009,sizeof(_Index1009)/sizeof(_Index1009[0]), 0x1009},
  { (subindex*)_Index100A,sizeof(_Index100A)/sizeof(_Index100A[0]), 0x100A},
  { (subindex*)_Index1010,sizeof(_Index1010)/sizeof(_Index1010[0]), 0x1010},
  { (subindex*)_Index1011,sizeof(_Index1011)/sizeof(_Index1011[0]), 0x1011},
  { (subindex*)_Index1014,sizeof(_Index1014)/sizeof(_Index1014[0]), 0x1014},
  { (subindex*)_Index1015,sizeof(_Index1015)/sizeof(_Index1015[0]), 0x1015},
  { (subindex*)_Index1017,sizeof(_Index1017)/sizeof(_Index1017[0]), 0x1017},
  { (subindex*)_Index1018,sizeof(_Index1018)/sizeof(_Index1018[0]), 0x1018},
  { (subindex*)_Index1019,sizeof(_Index1019)/sizeof(_Index1019[0]), 0x1019},
  { (subindex*)_Index1029,sizeof(_Index1029)/sizeof(_Index1029[0]), 0x1029},
  //{ (subindex*)_Index1200,sizeof(_Index1200)/sizeof(_Index1200[0]), 0x1200},
	{ (subindex*)example_objdict_Index1280,sizeof(example_objdict_Index1280)/sizeof(example_objdict_Index1280[0]), 0x1280},
  { (subindex*)_Index1400,sizeof(_Index1400)/sizeof(_Index1400[0]), 0x1400},
  { (subindex*)_Index1401,sizeof(_Index1401)/sizeof(_Index1401[0]), 0x1401},
  { (subindex*)_Index1402,sizeof(_Index1402)/sizeof(_Index1402[0]), 0x1402},
  { (subindex*)_Index1403,sizeof(_Index1403)/sizeof(_Index1403[0]), 0x1403},
  { (subindex*)_Index1600,sizeof(_Index1600)/sizeof(_Index1600[0]), 0x1600},
  { (subindex*)_Index1601,sizeof(_Index1601)/sizeof(_Index1601[0]), 0x1601},
  { (subindex*)_Index1602,sizeof(_Index1602)/sizeof(_Index1602[0]), 0x1602},
  { (subindex*)_Index1603,sizeof(_Index1603)/sizeof(_Index1603[0]), 0x1603},
  { (subindex*)_Index1800,sizeof(_Index1800)/sizeof(_Index1800[0]), 0x1800},
  { (subindex*)_Index1801,sizeof(_Index1801)/sizeof(_Index1801[0]), 0x1801},
  { (subindex*)_Index1802,sizeof(_Index1802)/sizeof(_Index1802[0]), 0x1802},
  { (subindex*)_Index1803,sizeof(_Index1803)/sizeof(_Index1803[0]), 0x1803},
  { (subindex*)_Index1A00,sizeof(_Index1A00)/sizeof(_Index1A00[0]), 0x1A00},
  { (subindex*)_Index1A01,sizeof(_Index1A01)/sizeof(_Index1A01[0]), 0x1A01},
  { (subindex*)_Index1A02,sizeof(_Index1A02)/sizeof(_Index1A02[0]), 0x1A02},
  { (subindex*)_Index1A03,sizeof(_Index1A03)/sizeof(_Index1A03[0]), 0x1A03},
  { (subindex*)_Index1F80,sizeof(_Index1F80)/sizeof(_Index1F80[0]), 0x1F80},
  { (subindex*)_Index2014,sizeof(_Index2014)/sizeof(_Index2014[0]), 0x2014},
  { (subindex*)_Index2015,sizeof(_Index2015)/sizeof(_Index2015[0]), 0x2015},
  { (subindex*)_Index2016,sizeof(_Index2016)/sizeof(_Index2016[0]), 0x2016},
  { (subindex*)_Index2017,sizeof(_Index2017)/sizeof(_Index2017[0]), 0x2017},
  { (subindex*)_Index2100,sizeof(_Index2100)/sizeof(_Index2100[0]), 0x2100},
  { (subindex*)_Index2101,sizeof(_Index2101)/sizeof(_Index2101[0]), 0x2101},
  { (subindex*)_Index2102,sizeof(_Index2102)/sizeof(_Index2102[0]), 0x2102},
  { (subindex*)_Index2103,sizeof(_Index2103)/sizeof(_Index2103[0]), 0x2103},
  { (subindex*)_Index2104,sizeof(_Index2104)/sizeof(_Index2104[0]), 0x2104},
  { (subindex*)_Index2200,sizeof(_Index2200)/sizeof(_Index2200[0]), 0x2200},
  { (subindex*)_Index3000,sizeof(_Index3000)/sizeof(_Index3000[0]), 0x3000},
  { (subindex*)_Index4000,sizeof(_Index4000)/sizeof(_Index4000[0]), 0x4000},
  { (subindex*)_Index5400,sizeof(_Index5400)/sizeof(_Index5400[0]), 0x5400},
  { (subindex*)_Index5401,sizeof(_Index5401)/sizeof(_Index5401[0]), 0x5401},
  { (subindex*)_Index5402,sizeof(_Index5402)/sizeof(_Index5402[0]), 0x5402},
  { (subindex*)_Index5403,sizeof(_Index5403)/sizeof(_Index5403[0]), 0x5403},
  { (subindex*)_Index5404,sizeof(_Index5404)/sizeof(_Index5404[0]), 0x5404},
  { (subindex*)_Index5405,sizeof(_Index5405)/sizeof(_Index5405[0]), 0x5405},
  { (subindex*)_Index5406,sizeof(_Index5406)/sizeof(_Index5406[0]), 0x5406},
  { (subindex*)_Index5407,sizeof(_Index5407)/sizeof(_Index5407[0]), 0x5407},
  { (subindex*)_Index5408,sizeof(_Index5408)/sizeof(_Index5408[0]), 0x5408},
  { (subindex*)_Index5409,sizeof(_Index5409)/sizeof(_Index5409[0]), 0x5409},
  { (subindex*)_Index540A,sizeof(_Index540A)/sizeof(_Index540A[0]), 0x540A},
  { (subindex*)_Index540B,sizeof(_Index540B)/sizeof(_Index540B[0]), 0x540B},
  { (subindex*)_Index540C,sizeof(_Index540C)/sizeof(_Index540C[0]), 0x540C},
  { (subindex*)_Index540D,sizeof(_Index540D)/sizeof(_Index540D[0]), 0x540D},
  { (subindex*)_Index540E,sizeof(_Index540E)/sizeof(_Index540E[0]), 0x540E},
  { (subindex*)_Index540F,sizeof(_Index540F)/sizeof(_Index540F[0]), 0x540F},
  { (subindex*)_Index5410,sizeof(_Index5410)/sizeof(_Index5410[0]), 0x5410},
  { (subindex*)_Index5411,sizeof(_Index5411)/sizeof(_Index5411[0]), 0x5411},
  { (subindex*)_Index5412,sizeof(_Index5412)/sizeof(_Index5412[0]), 0x5412},
  { (subindex*)_Index5413,sizeof(_Index5413)/sizeof(_Index5413[0]), 0x5413},
  { (subindex*)_Index5414,sizeof(_Index5414)/sizeof(_Index5414[0]), 0x5414},
  { (subindex*)_Index5415,sizeof(_Index5415)/sizeof(_Index5415[0]), 0x5415},
  { (subindex*)_Index5416,sizeof(_Index5416)/sizeof(_Index5416[0]), 0x5416},
  { (subindex*)_Index5417,sizeof(_Index5417)/sizeof(_Index5417[0]), 0x5417},
  { (subindex*)_Index5418,sizeof(_Index5418)/sizeof(_Index5418[0]), 0x5418},
  { (subindex*)_Index5419,sizeof(_Index5419)/sizeof(_Index5419[0]), 0x5419},
  { (subindex*)_Index541A,sizeof(_Index541A)/sizeof(_Index541A[0]), 0x541A},
  { (subindex*)_Index541B,sizeof(_Index541B)/sizeof(_Index541B[0]), 0x541B},
  { (subindex*)_Index541C,sizeof(_Index541C)/sizeof(_Index541C[0]), 0x541C},
  { (subindex*)_Index541D,sizeof(_Index541D)/sizeof(_Index541D[0]), 0x541D},
  { (subindex*)_Index541E,sizeof(_Index541E)/sizeof(_Index541E[0]), 0x541E},
  { (subindex*)_Index541F,sizeof(_Index541F)/sizeof(_Index541F[0]), 0x541F},
  { (subindex*)_Index5420,sizeof(_Index5420)/sizeof(_Index5420[0]), 0x5420},
  { (subindex*)_Index5421,sizeof(_Index5421)/sizeof(_Index5421[0]), 0x5421},
  { (subindex*)_Index5422,sizeof(_Index5422)/sizeof(_Index5422[0]), 0x5422},
  { (subindex*)_Index5423,sizeof(_Index5423)/sizeof(_Index5423[0]), 0x5423},
  { (subindex*)_Index5424,sizeof(_Index5424)/sizeof(_Index5424[0]), 0x5424},
  { (subindex*)_Index5425,sizeof(_Index5425)/sizeof(_Index5425[0]), 0x5425},
  { (subindex*)_Index5426,sizeof(_Index5426)/sizeof(_Index5426[0]), 0x5426},
  { (subindex*)_Index5427,sizeof(_Index5427)/sizeof(_Index5427[0]), 0x5427},
  { (subindex*)_Index5428,sizeof(_Index5428)/sizeof(_Index5428[0]), 0x5428},
  { (subindex*)_Index5429,sizeof(_Index5429)/sizeof(_Index5429[0]), 0x5429},
  { (subindex*)_Index542A,sizeof(_Index542A)/sizeof(_Index542A[0]), 0x542A},
  { (subindex*)_Index542B,sizeof(_Index542B)/sizeof(_Index542B[0]), 0x542B},
  { (subindex*)_Index542C,sizeof(_Index542C)/sizeof(_Index542C[0]), 0x542C},
  { (subindex*)_Index542D,sizeof(_Index542D)/sizeof(_Index542D[0]), 0x542D},
  { (subindex*)_Index542E,sizeof(_Index542E)/sizeof(_Index542E[0]), 0x542E},
  { (subindex*)_Index542F,sizeof(_Index542F)/sizeof(_Index542F[0]), 0x542F},
  { (subindex*)_Index5430,sizeof(_Index5430)/sizeof(_Index5430[0]), 0x5430},
  { (subindex*)_Index5431,sizeof(_Index5431)/sizeof(_Index5431[0]), 0x5431},
  { (subindex*)_Index5432,sizeof(_Index5432)/sizeof(_Index5432[0]), 0x5432},
  { (subindex*)_Index5433,sizeof(_Index5433)/sizeof(_Index5433[0]), 0x5433},
  { (subindex*)_Index5434,sizeof(_Index5434)/sizeof(_Index5434[0]), 0x5434},
  { (subindex*)_Index5435,sizeof(_Index5435)/sizeof(_Index5435[0]), 0x5435},
  { (subindex*)_Index5436,sizeof(_Index5436)/sizeof(_Index5436[0]), 0x5436},
  { (subindex*)_Index603F,sizeof(_Index603F)/sizeof(_Index603F[0]), 0x603F},
  { (subindex*)_Index6040,sizeof(_Index6040)/sizeof(_Index6040[0]), 0x6040},
  { (subindex*)_Index6041,sizeof(_Index6041)/sizeof(_Index6041[0]), 0x6041},
  { (subindex*)_Index605A,sizeof(_Index605A)/sizeof(_Index605A[0]), 0x605A},
  { (subindex*)_Index6060,sizeof(_Index6060)/sizeof(_Index6060[0]), 0x6060},
  { (subindex*)_Index6061,sizeof(_Index6061)/sizeof(_Index6061[0]), 0x6061},
  { (subindex*)_Index6064,sizeof(_Index6064)/sizeof(_Index6064[0]), 0x6064},
  { (subindex*)_Index6065,sizeof(_Index6065)/sizeof(_Index6065[0]), 0x6065},
  { (subindex*)_Index606C,sizeof(_Index606C)/sizeof(_Index606C[0]), 0x606C},
  { (subindex*)_Index6071,sizeof(_Index6071)/sizeof(_Index6071[0]), 0x6071},
  { (subindex*)_Index6073,sizeof(_Index6073)/sizeof(_Index6073[0]), 0x6073},
  { (subindex*)_Index6074,sizeof(_Index6074)/sizeof(_Index6074[0]), 0x6074},
  { (subindex*)_Index6078,sizeof(_Index6078)/sizeof(_Index6078[0]), 0x6078},
  { (subindex*)_Index607A,sizeof(_Index607A)/sizeof(_Index607A[0]), 0x607A},
  { (subindex*)_Index607C,sizeof(_Index607C)/sizeof(_Index607C[0]), 0x607C},
  { (subindex*)_Index607E,sizeof(_Index607E)/sizeof(_Index607E[0]), 0x607E},
  { (subindex*)_Index607F,sizeof(_Index607F)/sizeof(_Index607F[0]), 0x607F},
  { (subindex*)_Index6081,sizeof(_Index6081)/sizeof(_Index6081[0]), 0x6081},
  { (subindex*)_Index6083,sizeof(_Index6083)/sizeof(_Index6083[0]), 0x6083},
  { (subindex*)_Index6084,sizeof(_Index6084)/sizeof(_Index6084[0]), 0x6084},
  { (subindex*)_Index6085,sizeof(_Index6085)/sizeof(_Index6085[0]), 0x6085},
  { (subindex*)_Index6087,sizeof(_Index6087)/sizeof(_Index6087[0]), 0x6087},
  { (subindex*)_Index6098,sizeof(_Index6098)/sizeof(_Index6098[0]), 0x6098},
  { (subindex*)_Index6099,sizeof(_Index6099)/sizeof(_Index6099[0]), 0x6099},
  { (subindex*)_Index609A,sizeof(_Index609A)/sizeof(_Index609A[0]), 0x609A},
  { (subindex*)_Index60F4,sizeof(_Index60F4)/sizeof(_Index60F4[0]), 0x60F4},
  { (subindex*)_Index60FE,sizeof(_Index60FE)/sizeof(_Index60FE[0]), 0x60FE},
  { (subindex*)_Index60FF,sizeof(_Index60FF)/sizeof(_Index60FF[0]), 0x60FF},
  { (subindex*)_Index6502,sizeof(_Index6502)/sizeof(_Index6502[0]), 0x6502},
  { (subindex*)_Index7001,sizeof(_Index7001)/sizeof(_Index7001[0]), 0x7001},
  { (subindex*)_Index7002,sizeof(_Index7002)/sizeof(_Index7002[0]), 0x7002},
  { (subindex*)_Index7003,sizeof(_Index7003)/sizeof(_Index7003[0]), 0x7003},
  { (subindex*)_Index7005,sizeof(_Index7005)/sizeof(_Index7005[0]), 0x7005},
  { (subindex*)_Index7006,sizeof(_Index7006)/sizeof(_Index7006[0]), 0x7006},
  { (subindex*)_Index7007,sizeof(_Index7007)/sizeof(_Index7007[0]), 0x7007},
  { (subindex*)_Index7009,sizeof(_Index7009)/sizeof(_Index7009[0]), 0x7009},
  { (subindex*)_Index700A,sizeof(_Index700A)/sizeof(_Index700A[0]), 0x700A},
  { (subindex*)_Index700B,sizeof(_Index700B)/sizeof(_Index700B[0]), 0x700B},
  { (subindex*)_Index700C,sizeof(_Index700C)/sizeof(_Index700C[0]), 0x700C},
  { (subindex*)_Index700D,sizeof(_Index700D)/sizeof(_Index700D[0]), 0x700D},
  { (subindex*)_Index700E,sizeof(_Index700E)/sizeof(_Index700E[0]), 0x700E},
  { (subindex*)_Index700F,sizeof(_Index700F)/sizeof(_Index700F[0]), 0x700F},
  { (subindex*)_Index7010,sizeof(_Index7010)/sizeof(_Index7010[0]), 0x7010},
  { (subindex*)_Index7011,sizeof(_Index7011)/sizeof(_Index7011[0]), 0x7011},
  { (subindex*)_Index7012,sizeof(_Index7012)/sizeof(_Index7012[0]), 0x7012},
};

const indextable * _scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)//(UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	//*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1002: i = 2;break;
		case 0x1003: i = 3;break;
		case 0x1005: i = 4;break;
		case 0x1006: i = 5;break;
		case 0x1007: i = 6;break;
		case 0x1008: i = 7;break;
		case 0x1009: i = 8;break;
		case 0x100A: i = 9;break;
		case 0x1010: i = 10;break;
		case 0x1011: i = 11;break;
		case 0x1014: i = 12;break;
		case 0x1015: i = 13;break;
		case 0x1017: i = 14;break;
		case 0x1018: i = 15;break;
		case 0x1019: i = 16;break;
		case 0x1029: i = 17;break;
		case 0x1200: i = 18;break;
		case 0x1400: i = 19;break;
		case 0x1401: i = 20;break;
		case 0x1402: i = 21;break;
		case 0x1403: i = 22;break;
		case 0x1600: i = 23;break;
		case 0x1601: i = 24;break;
		case 0x1602: i = 25;break;
		case 0x1603: i = 26;break;
		case 0x1800: i = 27;break;
		case 0x1801: i = 28;break;
		case 0x1802: i = 29;break;
		case 0x1803: i = 30;break;
		case 0x1A00: i = 31;break;
		case 0x1A01: i = 32;break;
		case 0x1A02: i = 33;break;
		case 0x1A03: i = 34;break;
		case 0x1F80: i = 35;break;
		case 0x2014: i = 36;break;
		case 0x2015: i = 37;break;
		case 0x2016: i = 38;break;
		case 0x2017: i = 39;break;
		case 0x2100: i = 40;break;
		case 0x2101: i = 41;break;
		case 0x2102: i = 42;break;
		case 0x2103: i = 43;break;
		case 0x2104: i = 44;break;
		case 0x2200: i = 45;break;
		case 0x3000: i = 46;break;
		case 0x4000: i = 47;break;
		case 0x5400: i = 48;break;
		case 0x5401: i = 49;break;
		case 0x5402: i = 50;break;
		case 0x5403: i = 51;break;
		case 0x5404: i = 52;break;
		case 0x5405: i = 53;break;
		case 0x5406: i = 54;break;
		case 0x5407: i = 55;break;
		case 0x5408: i = 56;break;
		case 0x5409: i = 57;break;
		case 0x540A: i = 58;break;
		case 0x540B: i = 59;break;
		case 0x540C: i = 60;break;
		case 0x540D: i = 61;break;
		case 0x540E: i = 62;break;
		case 0x540F: i = 63;break;
		case 0x5410: i = 64;break;
		case 0x5411: i = 65;break;
		case 0x5412: i = 66;break;
		case 0x5413: i = 67;break;
		case 0x5414: i = 68;break;
		case 0x5415: i = 69;break;
		case 0x5416: i = 70;break;
		case 0x5417: i = 71;break;
		case 0x5418: i = 72;break;
		case 0x5419: i = 73;break;
		case 0x541A: i = 74;break;
		case 0x541B: i = 75;break;
		case 0x541C: i = 76;break;
		case 0x541D: i = 77;break;
		case 0x541E: i = 78;break;
		case 0x541F: i = 79;break;
		case 0x5420: i = 80;break;
		case 0x5421: i = 81;break;
		case 0x5422: i = 82;break;
		case 0x5423: i = 83;break;
		case 0x5424: i = 84;break;
		case 0x5425: i = 85;break;
		case 0x5426: i = 86;break;
		case 0x5427: i = 87;break;
		case 0x5428: i = 88;break;
		case 0x5429: i = 89;break;
		case 0x542A: i = 90;break;
		case 0x542B: i = 91;break;
		case 0x542C: i = 92;break;
		case 0x542D: i = 93;break;
		case 0x542E: i = 94;break;
		case 0x542F: i = 95;break;
		case 0x5430: i = 96;break;
		case 0x5431: i = 97;break;
		case 0x5432: i = 98;break;
		case 0x5433: i = 99;break;
		case 0x5434: i = 100;break;
		case 0x5435: i = 101;break;
		case 0x5436: i = 102;break;
		case 0x603F: i = 103;break;
		case 0x6040: i = 104;break;
		case 0x6041: i = 105;break;
		case 0x605A: i = 106;break;
		case 0x6060: i = 107;break;
		case 0x6061: i = 108;break;
		case 0x6064: i = 109;break;
		case 0x6065: i = 110;break;
		case 0x606C: i = 111;break;
		case 0x6071: i = 112;break;
		case 0x6073: i = 113;break;
		case 0x6074: i = 114;break;
		case 0x6078: i = 115;break;
		case 0x607A: i = 116;break;
		case 0x607C: i = 117;break;
		case 0x607E: i = 118;break;
		case 0x607F: i = 119;break;
		case 0x6081: i = 120;break;
		case 0x6083: i = 121;break;
		case 0x6084: i = 122;break;
		case 0x6085: i = 123;break;
		case 0x6087: i = 124;break;
		case 0x6098: i = 125;break;
		case 0x6099: i = 126;break;
		case 0x609A: i = 127;break;
		case 0x60F4: i = 128;break;
		case 0x60FE: i = 129;break;
		case 0x60FF: i = 130;break;
		case 0x6502: i = 131;break;
		case 0x7001: i = 132;break;
		case 0x7002: i = 133;break;
		case 0x7003: i = 134;break;
		case 0x7005: i = 135;break;
		case 0x7006: i = 136;break;
		case 0x7007: i = 137;break;
		case 0x7009: i = 138;break;
		case 0x700A: i = 139;break;
		case 0x700B: i = 140;break;
		case 0x700C: i = 141;break;
		case 0x700D: i = 142;break;
		case 0x700E: i = 143;break;
		case 0x700F: i = 144;break;
		case 0x7010: i = 145;break;
		case 0x7011: i = 146;break;
		case 0x7012: i = 147;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status _PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index _firstIndex = {
  18, /* SDO_SVR */
  18, /* SDO_CLT */
  19, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  27, /* PDO_TRS */
  31 /* PDO_TRS_MAP */
};

const quick_index _lastIndex = {
  18, /* SDO_SVR */
  18, /* SDO_CLT */
  22, /* PDO_RCV */
  26, /* PDO_RCV_MAP */
  30, /* PDO_TRS */
  34 /* PDO_TRS_MAP */
};

const UNS16 _ObjdictSize = sizeof(_objdict)/sizeof(_objdict[0]); 

CO_Data ObjDict_Data = CANOPEN_NODE_DATA_INITIALIZER();

