#ifndef __PTZ_HORIZ_OBJDICT_H__
#define __PTZ_HORIZ_OBJDICT_H__

/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

#define SDO_Server_Node_ID    0x3		/* node id */
#define IS_SLAVE_MODE		  0 //0:Master 1:slave
#define Server_Transmit_SDO   0x600|SDO_Server_Node_ID 	/* 0 */
#define Client_Receive_SDO    0x580|SDO_Server_Node_ID 	/* 0 */

/* Prototypes of function provided by object dictionnary */
UNS32 PTZ_HORIZ_Master_valueRangePTZ_HORIZ_ (UNS8 typeValue, void * value);
const indextable * PTZ_HORIZ_Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* prototypes of function to be filled by app. */
void PTZ_HORIZ_Master_SDOtimeoutError(UNS8 line);
void PTZ_HORIZ_Master_heartbeatError(UNS8);

UNS8 PTZ_HORIZ_Master_canSend(Message *);

void PTZ_HORIZ_Master_initialisation(void);
void PTZ_HORIZ_Master_preOperational(void);
void PTZ_HORIZ_Master_operational(void);
void PTZ_HORIZ_Master_stopped(void);

void PTZ_HORIZ_Master_post_sync(void);
void PTZ_HORIZ_Master_post_TPDO(void);

/* Master node data struct */
extern CO_Data PTZ_HORIZ_Master_Data;

extern ODCallback_t Store_parameters_callbacks[];		/* Callbacks of index0x1010 */
extern ODCallback_t Restore_Default_Parameters_callbacks[];		/* Callbacks of index0x1011 */
extern UNS8 MasterMap1;		/* Mapped at index 0x2000, subindex 0x00*/
extern ODCallback_t MasterMap1_callbacks[];		/* Callbacks of index0x2000 */
extern UNS8 MasterMap2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 MasterMap3;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 MasterMap4;		/* Mapped at index 0x2003, subindex 0x00*/

#endif
